name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential
      - name: Configure project
        run: cmake -B build
      - name: Build project
        run: cmake --build build -- -j$(nproc)
      - name: Run tests
        run: ctest --test-dir build --output-on-failure
